// lib/core/di/injection.dart
// ─────────────────────────────────────────────────────────────────────────────
// Dependency injection root.
// Uses get_it as the service locator and injectable for code-gen registration.
// All medical-critical services are registered as singletons to prevent
// duplicate state (e.g., two IOB calculators with different internal clocks).
// ─────────────────────────────────────────────────────────────────────────────

import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'package:insulin_assistant/core/di/injection.config.dart';

/// Global service locator.
/// Direct use outside of DI-registered classes is discouraged;
/// prefer constructor injection everywhere.
final GetIt getIt = GetIt.instance;

/// Registers all dependencies generated by injectable.
/// Must be awaited before any `getIt<T>()` call.
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> configureDependencies() async => getIt.init();
