// lib/core/di/injection.config.dart
// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by injectable_generator — DO NOT EDIT MANUALLY.
// Run `flutter pub run build_runner build --delete-conflicting-outputs`
// to regenerate after adding/removing @injectable annotations.
//
// Stub provided here for Phase 1 compilability.
// Full generated output will replace this file after `build_runner`.
// ─────────────────────────────────────────────────────────────────────────────

// ignore_for_file: type=lint
// coverage:ignore-file

import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'package:insulin_assistant/core/database/database_manager.dart';
import 'package:insulin_assistant/core/logging/audit_logger.dart';
import 'package:insulin_assistant/core/security/encryption_service.dart';
import 'package:insulin_assistant/core/security/key_manager.dart';
import 'package:insulin_assistant/data/datasources/local/food_data_seeder.dart';

extension GetItInjectableX on GetIt {
  /// Registers all services.  Called by [configureDependencies].
  // ignore: unused_element
  Future<GetIt> init({
    String? environment,
    EnvironmentFilter? environmentFilter,
  }) async {
    // ── Singletons (medical critical — single instance required) ─────────────
    registerLazySingleton<KeyManager>(KeyManager.new);
    registerLazySingleton<EncryptionService>(
      () => EncryptionService(getIt<KeyManager>()),
    );
    registerLazySingleton<DatabaseManager>(DatabaseManager.new);
    registerLazySingleton<AuditLogger>(
      () => AuditLogger(getIt<DatabaseManager>()),
    );
    registerLazySingleton<FoodDataSeeder>(
      () => FoodDataSeeder(getIt<DatabaseManager>()),
    );

    return this;
  }
}
